import { useState, useMemo, useRef, useEffect } from 'react'

// provide a narrow runtime type for the compiled hooks object
declare global {
  interface Window {
    __COMPILED_HOOKS__?: Record<string, string>
  }
}
import type { FC } from 'react'
import HOOK_GROUPS from './hooksIndex'
import '../App.css'

// allow runtime-loaded Sucrase on window
declare global {
  interface Window {
    Sucrase?: {
      transform: (code: string, opts: { transforms: string[] }) => { code: string }
    }
  }
}

const HookDocs: FC = () => {
  const [selected, setSelected] = useState(() => HOOK_GROUPS[0].hooks[0].id)
  const [openGroups, setOpenGroups] = useState<Record<string, boolean>>(() => {
    const map: Record<string, boolean> = {}
    HOOK_GROUPS.forEach(g => (map[g.title] = true))
    return map
  })

  const findHook = (id: string) => {
    for (const g of HOOK_GROUPS) {
      const found = g.hooks.find(h => h.id === id)
      if (found) return found
    }
    return null
  }

  const current = findHook(selected)
  const [preferredLang, setPreferredLang] = useState<'js' | 'ts'>('js')
  // Always show advanced details (no toggle)

  // repo header info (owner/name can be customized)
  const [repoInfo, setRepoInfo] = useState<{ stars: number; url: string; fullName?: string } | null>(null)
  const repoOwner = 'kuldeepNageshwar17'
  const repoName = 'reactHookDirectory'
  const useDummyStar = true
  const dummyStars = 42

  // compiled snippets loaded from public/compiledHooks.json (generated by scripts/compile-hooks)
  const [compiledSnippets, setCompiledSnippets] = useState<Record<string, string> | null>(null)

  // load compiled snippets once on mount
  useEffect(() => {
    let mounted = true
      ; (async () => {
        try {
          const resp = await fetch('/compiledHooks.json')
          if (!resp.ok) throw new Error(`HTTP ${resp.status}`)
          const json = await resp.json()
          if (!mounted) return
            // cache on window for callers that expect it
            ; (window as unknown as Window).__COMPILED_HOOKS__ = json
          setCompiledSnippets(json)
        } catch {
          // leave compiledSnippets null — we'll fall back to showing the raw source
          setCompiledSnippets(null)
        }
      })()
    return () => { mounted = false }
  }, [])
  

  useEffect(() => {
    let mounted = true
    if (useDummyStar) {
      setRepoInfo({ stars: dummyStars, url: `https://github.com/${repoOwner}/${repoName}`, fullName: `${repoOwner}/${repoName}` })
      return () => { mounted = false }
    }

    ;(async () => {
      try {
        const resp = await fetch(`https://api.github.com/repos/${repoOwner}/${repoName}`)
        if (!resp.ok) return
        const j = await resp.json()
        if (!mounted) return
        setRepoInfo({ stars: j.stargazers_count || 0, url: j.html_url || `https://github.com/${repoOwner}/${repoName}`, fullName: j.full_name })
      } catch {
        /* ignore */
      }
    })()
    return () => { mounted = false }
  }, [useDummyStar, dummyStars, repoOwner, repoName])

  const displayedCode = useMemo(() => {
    if (!current) return ''
    if (preferredLang === 'ts') return current.source
    // prefer compiled snippets loaded at runtime
    if (compiledSnippets && compiledSnippets[current.id]) return compiledSnippets[current.id]
    if (typeof window !== 'undefined' && window.__COMPILED_HOOKS__ && window.__COMPILED_HOOKS__[current.id]) return window.__COMPILED_HOOKS__[current.id]
    // fallback: show raw source (TypeScript) when no compiled JS is available
    return current.source
  }, [current, preferredLang, compiledSnippets])

  // compiled snippets are loaded above; no client-side TS->JS conversion is used

  const codeRef = useRef<HTMLElement | null>(null)

  // Derived advanced info: when explicit advanced metadata isn't present,
  // show a helpful implementation summary extracted from the source.
  const derivedAdvanced = useMemo(() => {
    if (!current || !current.source) return null
    const src = current.source
    const lines = src.split('\n')
    // leading block comment (JSDoc) or consecutive single-line comments at top
    const blockMatch = src.match(/\/\*[\s\S]*?\*\//)
    const rawLeading = blockMatch ? blockMatch[0] : null
    // clean the comment: remove /* */ and leading '*' or '//' markers, preserve paragraphs
    const leadingParagraphs = rawLeading
      ? rawLeading
        .replace(/^\/\*+/, '')
        .replace(/\*+\/?$/, '')
        .split(/\r?\n/) // per-line cleanup
        .map(l => l.replace(/^\s*\*?\s?/, '').replace(/^\s*\/\/\s?/, ''))
        .map(l => l.replace(/\t/g, '    '))
        .join('\n')
        .split(/\n{2,}/)
        .map(p => p.trim())
        .filter(Boolean)
      : null

    // gather import statements
    const imports = Array.from(src.matchAll(/^import\s+([\s\S]*?)from\s+['"]([^'"]+)['"];?/gm)).map(m => ({ raw: m[0], spec: (m[1] || '').trim(), from: m[2] }))

    // detect common APIs/usages to give quick hints
    const uses: string[] = []
    if (/IntersectionObserver/.test(src) || /observe\(/.test(src)) uses.push('IntersectionObserver')
    if (/ResizeObserver/.test(src) || /resizeObserver/i.test(src)) uses.push('ResizeObserver')
    if (/localStorage/.test(src)) uses.push('localStorage')
    if (/fetch\(/.test(src) || /RequestInit/.test(src)) uses.push('fetch')
    if (/AbortController/.test(src)) uses.push('AbortController')
    if (/WebSocket/.test(src)) uses.push('WebSocket')
    if (/BroadcastChannel/.test(src)) uses.push('BroadcastChannel')
    if (/navigator\.geolocation/.test(src)) uses.push('Geolocation')
    if (/window\./.test(src) || /document\./.test(src)) uses.push('window/document')

    // make a data URL for viewing raw source quickly
    const rawHref = `data:text/plain;charset=utf-8,${encodeURIComponent(src)}`

    return {
      lines: lines.length,
      leadingParagraphs,
      imports,
      uses,
      rawHref
    }
  }, [current])

  useEffect(() => {
    if (!codeRef.current) return
    const el = codeRef.current
    // prefer compiled JS snippets loaded at runtime for the JS view
    const codeToShow = (preferredLang === 'js' && compiledSnippets && current && compiledSnippets[current.id]) ? compiledSnippets[current.id] : displayedCode
    // set raw code as textContent so Prism can parse it
    el.textContent = codeToShow || ''
    // set Prism language class
    el.className = `language-${preferredLang === 'ts' ? 'typescript' : 'javascript'}`
    // highlight via global Prism if available
    // access global Prism safely with a narrow shape
    const globalPrism = window as unknown as { Prism?: { highlightElement?: (el: Element) => void } }
    const P = globalPrism.Prism
    if (P && typeof P.highlightElement === 'function') {
      try {
        P.highlightElement(el)
      } catch {
        /* ignore highlight errors */
      }
    }
  }, [displayedCode, preferredLang, compiledSnippets, current])

  return (
    <div className="docs-app">
      <header className="docs-header">
        <div className="header-left">
          <a href="/" className="header-brand">React Hook Directory</a>
        </div>
        <div className="header-right">
          {repoInfo ? (
            <>
              <a href={repoInfo.url} target="_blank" rel="noreferrer" className="repo-link">{repoInfo.fullName || `${repoOwner}/${repoName}`}</a>
              <a href={`https://github.com/${repoOwner}/${repoName}/blob/main/CONTRIBUTING.md`} target="_blank" rel="noreferrer" className="contrib-link">Contribute</a>
              {/* GitHub button iframe: allows users to star the repo (opens auth if needed) */}
              <iframe
                title="GitHub Stars"
                src={`https://ghbtns.com/github-btn.html?user=${repoOwner}&repo=${repoName}&type=star&count=true`}
                frameBorder="0"
                scrolling="0"
                width="110"
                height="20"
                style={{ verticalAlign: 'middle' }}
              />
            </>
          ) : (
            <>
              <a href={`https://github.com/${repoOwner}/${repoName}`} target="_blank" rel="noreferrer" className="repo-link">View repo</a>
              <a href={`https://github.com/${repoOwner}/${repoName}/blob/main/CONTRIBUTING.md`} target="_blank" rel="noreferrer" className="contrib-link">Contribute</a>
              <iframe
                title="GitHub Stars"
                src={`https://ghbtns.com/github-btn.html?user=${repoOwner}&repo=${repoName}&type=star&count=true`}
                frameBorder="0"
                scrolling="0"
                width="110"
                height="20"
                style={{ verticalAlign: 'middle' }}
              />
            </>
          )}
        </div>
      </header>
      <div className="docs-root">
        <aside className="docs-sidebar">
          <div className="docs-brand">use-hooks — Docs</div>
          <div style={{ margin: '8px 0' }}>
            <a
              href={`https://github.com/${repoOwner}/${repoName}/blob/main/CONTRIBUTING.md`}
              target="_blank"
              rel="noreferrer"
              className="contrib-link sidebar-link"
            >
              Contribute
            </a>
          </div>
          {HOOK_GROUPS.map(group => (
            <div key={group.title} className="docs-group">
              <button
                className="docs-group-toggle"
                onClick={() => setOpenGroups(s => ({ ...s, [group.title]: !s[group.title] }))}
              >
                {group.title}
              </button>
              {openGroups[group.title] && (
                <ul className="docs-list">
                  {group.hooks.map(h => (
                    <li key={h.id}>
                      <button
                        className={`docs-link ${selected === h.id ? 'active' : ''}`}
                        onClick={() => setSelected(h.id)}
                      >
                        {h.name}
                      </button>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </aside>

        <main className="docs-main">
          {current ? (
            <>
              <h1>{current.name}</h1>
              <p className="muted">{current.description}</p>

              <section>
                <h3>Implementation</h3>

                <div className="codeEditor">
                  <div className="editorTabs">
                    <button
                      className={`tab ${preferredLang === 'js' ? 'active' : ''}`}
                      onClick={() => setPreferredLang('js')}
                    >
                      JS
                    </button>
                    <button
                      className={`tab ${preferredLang === 'ts' ? 'active' : ''}`}
                      onClick={() => setPreferredLang('ts')}
                    >
                      TS
                    </button>
                  </div>

                  <div className="editorContent">
                    <pre className="codeBlock line-numbers"><code ref={codeRef} className={`language-${preferredLang === 'ts' ? 'typescript' : 'javascript'}`} /></pre>
                  </div>
                </div>
              </section>
            </>
          ) : (
            <div>Select a hook from the sidebar to view its docs.</div>
          )}

          {/* Details shown after the code on the main screen */}
          {current && (
            <section className="details-after-code">
              <div className="compact-panel">
                <h4>Quick facts</h4>
                {current.signature && <pre className="sig">{current.signature}</pre>}
                {current.summary && <p className="summary">{current.summary}</p>}

                {current.params && current.params.length > 0 && (
                  <div className="params">
                    <strong>Params</strong>
                    <ul>
                      {current.params.map(p => (
                        <li key={p.name}>
                          <code>{p.name}</code>
                          {p.type ? <em>: {p.type}</em> : null}
                          {p.default ? <span> (default: {p.default})</span> : null}
                          {p.desc ? <div className="param-desc">{p.desc}</div> : null}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {current.returns && (
                  <div className="returns">
                    <strong>Returns</strong>
                    <div>{current.returns}</div>
                  </div>
                )}

                {current.related && current.related.length > 0 && (
                  <div className="related">
                    <strong>Related</strong>
                    <div className="related-list">
                      {current.related.map(r => (
                        <button key={r} className="related-pill" onClick={() => {
                          const found = HOOK_GROUPS.flatMap(g => g.hooks).find(h => h.id === r)
                          if (found) setSelected(found.id)
                        }}>{r}</button>
                      ))}
                    </div>
                  </div>
                )}
              </div>


              <div className="advanced-panel">
                {/* explicit advanced fields */}
                {current.motivation && (
                  <section>
                    <h5>Motivation</h5>
                    <p>{current.motivation}</p>
                  </section>
                )}
                {current.behaviour && (
                  <section>
                    <h5>Behaviour</h5>
                    <p>{current.behaviour}</p>
                  </section>
                )}
                {current.edgeCases && (
                  <section>
                    <h5>Edge cases</h5>
                    <p>{current.edgeCases}</p>
                  </section>
                )}
                {current.performance && (
                  <section>
                    <h5>Performance</h5>
                    <p>{current.performance}</p>
                  </section>
                )}
                {current.testing && (
                  <section>
                    <h5>Testing</h5>
                    <p>{current.testing}</p>
                  </section>
                )}
                {current.tsTips && (
                  <section>
                    <h5>TypeScript tips</h5>
                    <p>{current.tsTips}</p>
                  </section>
                )}
                {current.accessibility && (
                  <section>
                    <h5>Accessibility</h5>
                    <p>{current.accessibility}</p>
                  </section>
                )}
                {current.links && current.links.length > 0 && (
                  <section>
                    <h5>Links</h5>
                    <ul>
                      {current.links.map((l, i) => (
                        <li key={i}><a href={l.url} target="_blank" rel="noreferrer">{l.label || l.url}</a></li>
                      ))}
                    </ul>
                  </section>
                )}

                {/* derived implementation fallback */}
                {!current.motivation && !current.behaviour && !current.edgeCases && !current.performance && !current.testing && !current.tsTips && !current.accessibility && (!current.links || current.links.length === 0) && typeof derivedAdvanced !== 'undefined' && derivedAdvanced && (
                  <section>
                    <h5>Implementation overview</h5>
                    {/* Render leading comment as paragraphs for spacing */}
                    {derivedAdvanced.leadingParagraphs && derivedAdvanced.leadingParagraphs.length > 0 ? (
                      derivedAdvanced.leadingParagraphs.map((para, i) => (
                        <p key={i} className="muted">{para}</p>
                      ))
                    ) : (
                      <p className="muted">No top-level comment found — showing implementation hints.</p>
                    )}
                    <div style={{ marginTop: 8 }}>
                      <strong>Size</strong>
                      <div>{derivedAdvanced.lines} lines</div>
                    </div>

                    {/* Show how to import this hook (local + package examples) */}
                    <div style={{ marginTop: 8 }}>
                      <strong>How to import</strong>
                      <pre className="sig">{`import ${current.name} from '../hooks/${current.id}'`}</pre>
                      <pre className="sig">{`import { ${current.name} } from 'use-hooks'`}</pre>
                    </div>

                    {derivedAdvanced.uses && derivedAdvanced.uses.length > 0 && (
                      <div style={{ marginTop: 8 }}>
                        <strong>Detected APIs</strong>
                        <div>{derivedAdvanced.uses.join(', ')}</div>
                      </div>
                    )}
                    <div style={{ marginTop: 10 }}>
                      <a className="related-pill" href={derivedAdvanced.rawHref} target="_blank" rel="noreferrer">View raw source</a>
                    </div>
                  </section>
                )}
              </div>

            </section>
          )}
        </main>
      </div>
    </div>
  )
}

export default HookDocs
